name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install/set up CMake
      run: sudo apt-get install -y cmake

    - name: Install/set up dependencies
      run: sudo apt-get install -y libboost-test-dev

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./gs_test

on:
  pull:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install/set up CMake
      run: sudo apt-get install -y cmake

    - name: Install/set up dependencies
      run: sudo apt-get install -y libboost-test-dev

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./gs_test


